conn SYSTEM/12345678

GRANT ALL PRIVILEGES TO s200042151;

conn s200042151/cse4308

--1--

SELECT DISTINCT ACT_FIRSTNAME, ACT_LASTNAME
FROM ACTOR, DIRECTOR
WHERE ACTOR.ACT_FIRSTNAME = DIRECTOR.DIR_FIRSTNAME AND ACTOR.ACT_LASTNAME = DIRECTOR.DIR_LASTNAME;


--WITH INTERSECTION--
SELECT ACT_FIRSTNAME, ACT_LASTNAME
FROM ACTOR
INTERSECT
SELECT DIR_FIRSTNAME, DIR_LASTNAME
FROM DIRECTOR;


--2--

SELECT ACT_FIRSTNAME
FROM ACTOR
UNION ALL
SELECT DIR_FIRSTNAME
FROM DIRECTOR;

--3--

SELECT DISTINCT MOV_TITLE
FROM MOVIE
WHERE MOVIE.MOV_ID NOT IN(SELECT MOV_ID FROM RATING);

--WITH MINUS--
SELECT MOV_TITLE
FROM MOVIE
MINUS
SELECT MOV_TITLE
FROM MOVIE, RATING
WHERE MOVIE.MOV_ID = RATING.MOV_ID;


--4--

SELECT AVG(REV_STARS) AS AVG_RATING
FROM RATING;

--5--

SELECT MOVIE.MOV_TITLE, MIN(REV_STARS) AS MIN_STARS 
FROM RATING JOIN MOVIE ON RATING.MOV_ID = MOVIE.MOV_ID
GROUP BY MOVIE.MOV_TITLE
ORDER BY MIN_STARS DESC;

--6--

SELECT ACTOR.ACT_LASTNAME, COUNT(REV_STARS) AS CNT_STARS
FROM CASTS JOIN ACTOR ON CASTS.ACT_ID = ACTOR.ACT_ID 
     JOIN RATING ON CASTS.MOV_ID = RATING.MOV_ID
GROUP BY ACTOR.ACT_LASTNAME
ORDER BY CNT_STARS;


--7--

SELECT ACTOR.ACT_LASTNAME, AVG(MOVIE.MOV_TIME) AS AVG_TIME
FROM CASTS JOIN ACTOR ON CASTS.ACT_ID = ACTOR.ACT_ID
     JOIN MOVIE ON CASTS.MOV_ID = MOVIE.MOV_ID
     JOIN DIRECTION ON CASTS.MOV_ID = DIRECTION.MOV_ID
     JOIN DIRECTOR ON DIRECTION.DIR_ID = DIRECTOR.DIR_ID
WHERE DIRECTOR.DIR_FIRSTNAME NOT IN ('James') AND DIRECTOR.DIR_LASTNAME NOT IN ('Cameron')
GROUP BY ACTOR.ACT_LASTNAME;

--WITH HAVING CLAUSE--
--problem--
SELECT ACTOR.ACT_LASTNAME, AVG(MOVIE.MOV_TIME) AS AVG_TIME
FROM CASTS JOIN ACTOR ON CASTS.ACT_ID = ACTOR.ACT_ID
     JOIN MOVIE ON CASTS.MOV_ID = MOVIE.MOV_ID
     JOIN DIRECTION ON CASTS.MOV_ID = DIRECTION.MOV_ID
     JOIN DIRECTOR ON DIRECTION.DIR_ID = DIRECTOR.DIR_ID
GROUP BY ACTOR.ACT_LASTNAME
HAVING DIRECTOR.DIR_FIRSTNAME NOT IN ('James') AND DIRECTOR.DIR_LASTNAME NOT IN ('Cameron');

--8--

SELECT MAX(DIR_FIRSTNAME) FIRSTNAME, MAX(DIR_LASTNAME) LASTNAME, MAX(A.REVIEW_AVERAGE)
FROM DIRECTOR D1, DIRECTION D2, RATING R, (     SELECT M.MOV_ID, avg(REV_STARS) REVIEW_AVERAGE
                                                FROM RATING R, MOVIE M
                                                WHERE M.MOV_ID = R.MOV_ID
                                                GROUP BY M.MOV_ID) A
WHERE (D1.DIR_ID = D2.DIR_ID) AND (D2.MOV_ID = R.MOV_ID);



SELECT A.FIRSTNAME, A.LASTNAME, A.REVIEW_AVERAGE
FROM (SELECT *
    FROM(   SELECT D1.DIR_FIRSTNAME FIRSTNAME, D1.DIR_LASTNAME LASTNAME, avg(REV_STARS) REVIEW_AVERAGE
            FROM RATING R, DIRECTOR D1, DIRECTION D2
            WHERE (D2.MOV_ID = R.MOV_ID) and (D2.DIR_ID = D1.DIR_ID)
            GROUP BY (D1.DIR_FIRSTNAME, D1.DIR_LASTNAME))
    ORDER BY REVIEW_AVERAGE DESC) A
WHERE ROWNUM <= 1;



--WITH ALL--
SELECT MAX(ALL DIR_FIRSTNAME) FIRSTNAME, MAX(ALL DIR_LASTNAME) LASTNAME, MAX(A.REVIEW_AVERAGE)
FROM DIRECTOR D1, DIRECTION D2, RATING R, (     SELECT ALL M.MOV_ID, avg(REV_STARS) REVIEW_AVERAGE
                                                FROM RATING R, MOVIE M
                                                WHERE M.MOV_ID = R.MOV_ID
                                                GROUP BY M.MOV_ID) A
WHERE (D1.DIR_ID = D2.DIR_ID) AND (D2.MOV_ID = R.MOV_ID);



--9--

SELECT MOVIE.MOV_ID, MOVIE.MOV_TITLE, MOVIE.MOV_YEAR, MOVIE.MOV_LANGUAGE,MOVIE.MOV_RELEASEDATE,MOVIE.MOV_COUNTRY,MOV_TIME
FROM ACTOR, DIRECTOR, DIRECTION, MOVIE
WHERE  ACTOR.ACT_FIRSTNAME = DIRECTOR.DIR_FIRSTNAME AND ACTOR.ACT_LASTNAME = DIRECTOR.DIR_LASTNAME AND
        DIRECTOR.DIR_ID = DIRECTION.DIR_ID AND
        DIRECTION.MOV_ID = MOVIE.MOV_ID
--10--

SELECT MOVIE.MOV_TITLE, AVG(NVL(REV_STARS,0)) AS AVG_STARS 
FROM RATING JOIN MOVIE ON RATING.MOV_ID = MOVIE.MOV_ID
GROUP BY MOVIE.MOV_TITLE
HAVING AVG(NVL(REV_STARS,0)) > 7;

--WITHOUT HAVING CLAUSE--

SELECT MOV_TITLE, AVG_RATING
FROM    (SELECT MOV_TITLE, AVG(NVL(REV_STARS,0)) AS AVG_RATING
        FROM MOVIE, RATING
        WHERE MOVIE.MOV_ID = RATING.MOV_ID
        GROUP BY MOVIE.MOV_TITLE)
WHERE AVG_RATING > 7;

--11--

SELECT DISTINCT MOV_TITLE, AVG_RATING
FROM    (SELECT MOV_TITLE, AVG(NVL(REV_STARS,0)) AS AVG_RATING
        FROM MOVIE, RATING
        WHERE MOVIE.MOV_ID = RATING.MOV_ID
        GROUP BY MOVIE.MOV_TITLE)
WHERE AVG_RATING > (
        SELECT AVG(REV_STARS) AS AVG_RATING
        FROM RATING);



--12--

-- SELECT MOV_TITLE, AVG(NVL(REV_STARS,0)) AS AVG_RATING
--         FROM MOVIE, RATING
--         WHERE MOVIE.MOV_ID = RATING.MOV_ID
--         GROUP BY MOVIE.MOV_TITLE;

SELECT DISTINCT MOV_TITLE,(SELECT AVG(NVL(REV_STARS,0))
                        FROM RATING
                        WHERE MOVIE.MOV_ID = RATING.MOV_ID)
FROM MOVIE, RATING
WHERE MOVIE.MOV_ID = RATING.MOV_ID;

--13--

SELECT ACT_FIRSTNAME ,COUNT(*) AS Occurrence 
FROM ACTOR 
WHERE ACT_GENDER = 'F'
GROUP BY ACT_FIRSTNAME HAVING COUNT(*)>1; 

--14--

