--> a <--

SELECT D.NAME, COUNT(DS.NAME)
FROM DIVISION D NATURAL JOIN DISTRICT DS
GROUPBY D.NAME;

--> b <--
SELECT C.DISTRICT, COUNT(C.NID)
FROM CITIZEN C NATURAL JOIN DISTRICT D
HAVING COUNT(C.NID) >= 20000
GROUPBY C.DISTRICT;

--> c <--
SELECT COUNT(OCCURENCE_ID)
FROM CENTRALSYSTEM CS, CITIZEN C, LICENSE L
WHERE C.NID = "210" AND C.LICENSE_ID = L.LICENSE_ID AND D.LICENSE_ID = CS.LICENSE_ID;

--> d <--
SELECT ROWNUM AS RANK, H.NAME
FROM(SELECT H.NAME, COUNT(A.ADMISSION_ID)
     FROM HOSPITAL H, ADMISSION A
     WHERE H.HOSPITAL_REG_ID = A.HOSPITAL_ID
     GROUPBY H.NAME)
WHERE ROWNUM <= 5;

--> e <--
SELECT C.BLOOD_GROUP
FROM CITIZEN C, HOSPITAL H, ADMISSION A
WHERE C.NID = A.NID AND A.NID = H.NID;

--> f <--
SELECT D.NAME, (TOTAL/D.SIZE)
FROM(SELECT D.NAME, COUNT(C.NID) AS TOTAL
     FROM DIVISION D, CITIZEN C
     WHERE C.DIVISION_NAME = D.NAME
     GROUPBY D.NAME);

--> g <--
SELECT ROWNUM AS RANK, D.NAME
FROM(SELECT D.NAME, (TOTAL/D.SIZE)
     FROM(SELECT D.NAME, COUNT(C.NID) AS TOTAL
     FROM DIVISION D, CITIZEN C
     WHERE C.DIVISION_NAME = D.NAME
     GROUPBY D.NAME))
WHERE ROWNUM <= 3;

--> h <--
SELECT DS.NAME, COUNT(CS.OCCURENCE_ID)
FROM DISTRICT DS, CITIZEN C, LICENSE L, CENTRAL_SYSTEM CS
WHERE DS.NAME = C.DISTRICT AND C.LICENSE_ID = D.LICENSE_ID AND D.LICENSE_ID = CS.LICENSE_ID
GROUPBY DS.NAME;

--> i <--
SELECT D.NAME
FROM(SELECT D.NAME, COUNT(CS.OCCURENCE_ID) AS OCCURENCE
        FROM DIVISION D, CITIZEN C, LICENSE L, CENTRAL_SYSTEM CS
        WHERE D.NAME = C.DIVISION AND C.LICESNSE_ID = L.LICENSE_ID AND L.LICENSE_ID=CS.LICENSE_ID
        GROUPBY D.NAME
        ORDERBY OCCURENCE ASC)
WHERE ROWNUM <= 1;

--> j <--
SELECT COUNT(CS.OCCURENCE_ID)
FROM LICENSE L, CENTRAL_SYSTEM CS
WHERE L.TYPE = "PROFESSIONAL" AND L.TYPE = "NON-PROFESSIONAL";

--> k <--
SELECT C.NAME
FROM(SELECT C.NAME, (A.RELEASE_DATE - A.DATEOFADMISSION) AS TIME
    FROM CITIZEN C, ADMISSION A
    WHERE C.NID = A.NID
    ORDERBY TIME DESC)
WHERE ROWNUM <= 1;

--> l <--
SELECT D.NAME
FROM(SELECT D.NAME, COUNT(C.NID) AS TOTAL
    FROM DIVISION D, CITIZEN C
    WHERE D.NAME=C.DIVISION AND GETDATE()-C.DOB>= 15 AND GETDATE()-C.DOB <= 30
    ORDERBY TOTAL)
WHERE ROWNUM <= 1;

--> m <--
SELECT C.NAME
FROM CITIZEN C, LICENSE L
WHERE C.LICENSE_ID = D.LICENSE_ID AND GETDATE()>D.EXP_DATE;

--> n <--
SELECT C.NAME, COUNT(CS.OCCURENCE_ID)
FROM CITIZEN C, LICENSE L, CENTRAL_SYSTEM CS
WHERE C.LICENSE_ID = D.LICENSE_ID AND D.LICENSE_ID = CS.LICENSE_ID AND GETDATE()>D.EXP_DATE;

--> o <--
SELECT C.NAME
FROM CITIZEN C, LICENSE L
WHERE C.LICENSE_ID = D.LICENSE_ID;
MINUS
SELECT C.NAME
FROM CITIZEN C, LICENSE L, CENTRAL_SYSTEM CS
WHERE C.LICENSE_ID = D.LICENSE_ID AND D.LICENSE_ID = CS.LICENSE_ID;

--> p <--
SELECT D.NAME, CS.NUMBER_DEATHS
FROM DIVISION D, CITIZEN C, LICENSE L, CENTRAL_SYSTEM CS
WHERE D.NAME = C.DIVISION AND C.LICENSE_ID = L.LICENSE_ID AND L.LICENSE_ID = CS.LICENSE_ID;

--> q <--
SELECT C.NAME
FROM CITIZEN C, LICENSE L
WHERE (L.ISSUE_DATE - GETDATE())<=22 OR (L.ISSUE_DATE - GETDATE())>=40;

--> r <--
SELECT C.NAME
FROM CITIZEN C, LICENSE L, CENTRAL_SYSTEM CS, ADMISSION A
WHERE C.LICENSE_ID = L.LICENSE_ID AND L.LICENSE_ID = CS.LICENSE_ID AND C.NID = A.NID AND CS.DATE_TIME_ACCIDENT = A.DATEOFADMISSION;

--> s <--
SELECT H.NAME
FROM(SELECT H.NAME, COUNT(C.NID) AS TOTAL
     FROM HOSPITAL H, ADMISSION A, CITIZEN C
     WHERE C.DIVISION_NAME = "DHAKA" AND C.NID = A.NID AND A.HOSPITAL_ID = H.HOSPITAL_REG_ID
     GROUPBY H.NAME
     ORDERBY TOTAL DESC)
WHERE ROWNUM <= 1;

--> t <--
SELECT C.NAME
FROM CITIZEN C, LICENSE L, CENTRAL_SYSTEM CS
WHERE C.LICENSE_ID = L.LICENSE_ID AND L.LICENSE_ID = CS.LICENSE_ID
MINUS
SELECT C.NAME
FROM CITIZEN C, LICENSE L, CENTRAL_SYSTEM CS
WHERE C.LICENSE_ID = L.LICENSE_ID AND L.LICENSE_ID = CS.LICENSE_ID AND C.DISTRICT_NAME = CS.LOCATION;